backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Category", name: "category", widget: "select", options: ["PGA Tour", "LIV Golf", "DP World Tour", "The Majors", "Opinion", "Analysis", "Equipment", "Rankings"]}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
